# Generated by Django 4.2.5 on 2023-09-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raid_object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_name', models.CharField(max_length=64)),
                ('obj_val', models.CharField(max_length=64)),
                ('obj_img', models.ImageField(upload_to='obj_images')),
                ('obj_raid', models.JSONField()),
                ('obj_drop_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Raid_tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=64)),
                ('tool_val', models.CharField(max_length=64)),
                ('tool_img', models.ImageField(upload_to='tool_images')),
                ('tool_res', models.JSONField()),
                ('tool_drop_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=64)),
                ('res_val', models.CharField(max_length=64)),
                ('res_img', models.ImageField(upload_to='res_images')),
            ],
        ),
    ]
